#--------------------------------- WARNING!!! ---------------------------------#
# This file is auto-generated by `cubemx_cmake` tool, any modification to this #
# file will be lost at the next execution of the generator. If you want to     #
# tweak this file, please define a custom ERB template. Check out the documen- #
# tation of `cubemx_cmake` for more information.                               #
#--------------------------------- WARNING!!! ---------------------------------#

set(LD_SCRIPT ${CMAKE_SOURCE_DIR}/stm32cube/stm32f412zgtx_flash.ld)
set(CUBE_SOURCES
    stm32cube/drivers/bsp/stm32412g_discovery_sd.c
    stm32cube/drivers/bsp/stm32412g_discovery.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_sram.c
    stm32cube/drivers/hal/src/stm32f4xx_hal.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_fsmc.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_can.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_gpio.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_gpio.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_dma.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_dma_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_dma.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_rcc.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_rcc_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_rcc.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_cortex.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_flash.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_flash_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_flash_ramfunc.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_pwr.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_pwr_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_pwr.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_uart.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_sd.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_sdmmc.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_i2c.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_i2c_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_i2c.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_tim.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_tim_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_tim.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_rtc.c
    stm32cube/drivers/hal/src/stm32f4xx_hal_rtc_ex.c
    stm32cube/drivers/hal/src/stm32f4xx_ll_rtc.c
    stm32cube/middlewares/fatfs/src/drivers/sd_diskio_template.c
    stm32cube/middlewares/fatfs/src/diskio.c
    stm32cube/middlewares/fatfs/src/ff_gen_drv.c
    stm32cube/middlewares/fatfs/src/ff.c
    stm32cube/middlewares/fatfs/src/option/syscall.c
    stm32cube/startup/startup_stm32f412zx.s)
set(ALL_SOURCES ${SOURCES} ${CUBE_SOURCES})

set(CMAKE_C_COMPILER   arm-none-eabi-gcc)
set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(CMAKE_ASM_COMPILER arm-none-eabi-gcc)
set(OBJCOPY_BIN        arm-none-eabi-objcopy)

set(CUBE_C_FLAGS    "-mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -fdata-sections -ffunction-sections")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${CUBE_C_FLAGS}")

set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "")   # Removes -rdynamic
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "") # Removes -rdynamic
set(CMAKE_EXE_LINKER_FLAGS "${CUBE_C_FLAGS} -T${LD_SCRIPT} -Wl,--gc-sections")

set_source_files_properties(
  ${CUBE_SOURCES} PROPERTIES
  COMPILE_FLAGS "-Wno-pedantic -Wno-unused-parameter")

add_executable(${BIN_NAME} ${ALL_SOURCES})

set_target_properties(${BIN_NAME} PROPERTIES COMPILE_FLAGS ${CUBE_C_FLAGS})
target_include_directories(${BIN_NAME}
  PRIVATE stm32cube/drivers/cmsis/include
  PRIVATE stm32cube/drivers/bsp
  PRIVATE stm32cube/drivers/hal/include
  PRIVATE stm32cube/drivers/hal/include/Legacy
  PRIVATE stm32cube/middlewares/fatfs/src/drivers
  PRIVATE stm32cube/middlewares/fatfs/src)
target_compile_definitions(${BIN_NAME}
  PRIVATE "__weak=__attribute__((weak))"
  PRIVATE "__packed=__attribute__((__packed__))"
  PRIVATE STM32F412Zx
  PRIVATE USE_HAL_DRIVER)
target_link_libraries(${BIN_NAME} "-lc -lm -lnosys")

add_custom_command(
  TARGET ${BIN_NAME} POST_BUILD
  COMMAND ${OBJCOPY_BIN} -O binary -S ${BIN_NAME} ${BIN_NAME}.bin)
add_custom_target(upload
  COMMAND st-flash write ${BIN_NAME}.bin 0x08000000
  DEPENDS ${BIN_NAME})
